spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn

spring.datasource.username=root

spring.datasource.password=sam123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=validate


# Reduce Spring Boot logs
logging.level.org.springframework=WARN

# Show only your application logs
logging.level.com.cognizant=INFO

# Hide Hibernate SQL logs
logging.level.org.hibernate.SQL=OFF